@baseUrl = http://localhost:6400

### Health
GET {{baseUrl}}/api/v1/health

### List All Todos
GET {{baseUrl}}/api/v1/todos?completed=false

### Get a specific Todo
GET {{baseUrl}}/api/v1/todos/6

### Create a Todo
POST {{baseUrl}}/api/v1/todos
Content-Type: application/json

{
    "title": "Test Todo",
    "description": "This is a test todo",
    "completed": false,
    "deadline_at": "2025-04-11T16:04:00.799263"
}

### Update a Todo
PUT {{baseUrl}}/api/v1/todos/2
Content-Type: application/json

{
    "title": "updated title",
    "completed": "true"
}

### Delete a Todo
DELETE {{baseUrl}}/api/v1/todos/1
